#:schema https://raw.githubusercontent.com/jdx/mise/refs/heads/main/schema/mise.json

[tools]
node = "26"
pnpm = "11"

[shell_alias]
specify = "mise exec pipx:git+https://github.com/github/spec-kit.git -- specify"
shadcn = "mise exec npm:shadcn@latest -- shadcn"
