name: CI

on:
  push:
    branches:
      - main

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          cache: true
          version: ^11

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version-file: .tool-versions

      - run: pnpm install

      - run: pnpm tsc

      - run: pnpm semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
